spring:
  application:
    name: "gatewayserver"
  config:
    import:
      - "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
    httpclient:
      connect-timeout: 100000
      response-timeout: 100s
  data:
    redis:
      connect-timeout: 10s
      host: localhost
      port: 6379
      timeout: 5s

management:
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "gatewayserver"
    description: "Gateway server microservice"
    version: "1.0"

logging:
  level:
    com:
      monit:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000